services:
  postgres:
    image: postgres:16
    container_name: cricket_pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: cricket
      POSTGRES_PASSWORD: cricket123
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
